// <auto-generated />
using System;
using CheckInApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckInApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721191500_RenomearSenhaParaSenhaHash")]
    partial class RenomearSenhaParaSenhaHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("CheckInApp.Domain.Entities.Quarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quartos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadeMaxima = 2,
                            Numero = 101,
                            Status = 0,
                            ValorDiaria = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            CapacidadeMaxima = 3,
                            Numero = 102,
                            Status = 0,
                            ValorDiaria = 150.00m
                        },
                        new
                        {
                            Id = 3,
                            CapacidadeMaxima = 4,
                            Numero = 103,
                            Status = 0,
                            ValorDiaria = 200.00m
                        });
                });

            modelBuilder.Entity("CheckInApp.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acompanhantes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Checkin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Checkout")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CheckoutComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeHospede")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeHospede")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxasAdicionais")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("CheckInApp.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "000.000.000-00",
                            Email = "admin@hotel.com",
                            Nome = "Administrador do Sistema",
                            NumeroCelular = "00000000000",
                            Role = 1,
                            SenhaHash = "$2a$11$eu5r2bWUTUOLFjUYQdidFuGzO0I/4ZMf0UUtX3pym44HaBKKd9CMq"
                        });
                });

            modelBuilder.Entity("CheckInApp.Domain.Entities.Quarto", b =>
                {
                    b.OwnsOne("CheckInApp.Domain.Entities.Hospede", "HospedeAtual", b1 =>
                        {
                            b1.Property<int>("QuartoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "Cpf");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasAnnotation("Relational:JsonPropertyName", "nomeHospede");

                            b1.HasKey("QuartoId");

                            b1.ToTable("Quartos");

                            b1.WithOwner()
                                .HasForeignKey("QuartoId");
                        });

                    b.Navigation("HospedeAtual");
                });
#pragma warning restore 612, 618
        }
    }
}
